name: CI/CD - Angular App

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  # Nombre de la imagen (github.repository asume usuario/repo)
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Necesario para subir a GHCR
      security-events: write # Necesario para subir reportes de Trivy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Setup y Tests
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      # (Opcional) Aquí iría 'npm run test'

      # 2. Análisis de Seguridad Estático (SAST) - SonarCloud
      # REQUIERE: Configurar SONAR_TOKEN en Secrets y SONAR_ORG en variables
      # Si no tienes cuenta aun, comenta este paso para probar primero el build.
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 3. Escaneo de vulnerabilidades (Trivy FS)
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # --- NUEVO: Convertir nombre a minúsculas ---
      # Esto coge 'ales-fava/DevOpsLab-MyWebApp' y lo convierte en 'ales-fava/devopslab-mywebapp'
      - name: Convert image name to lowercase
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      # 4. Login en GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Construcción y Subida de Imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # 6. Escaneo de la imagen construida (Container Security)
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
